version: '1'
services:

  mongoDB:
    image: mongo
    restart: always
    ports:
      - 27017:27017 
   
  collection:
    image: maluyvova/collection  
    restart: always
    ports:
      - 80:3000
    environment:
      MONGO_DATABASE_URL: mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000
